name: Trigger External Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name to greet'
        required: true

jobs:
  trigger-other:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Github-Actions workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: kishore-Anbu/Github-Actions
          event-type: trigger-manual
          client-payload: |
            {
              "username": "${{ github.event.inputs.name }}"
            }
