name: Test NuGet Composite Action

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test-nuget-action:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install NuGet
      - name: Install NuGet
        run: |
          curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe

      # Step 3: Verify NuGet Version
      - name: Verify NuGet Version
        run: .\nuget.exe help

      # Step 4: Use the Composite Action
      - name: Run NuGet Composite Action
        uses: Kishore-Anbu/Github-Actions/.github/actions/nuget-composite-action@main
        with:
          taskType: 'restore' # Specify the task type (command, installer, restore)
          solution: '**/*.sln' # Path to solution or packages.config
          verbosity: 'Detailed' # Verbosity level
          #selectOrConfig: 'select' # Feeds to use (select or config)
          #feed: 'https://api.nuget.org/v3/index.json' # Required if selectOrConfig is 'select'
          nugetConfigPath: './NuGet.config' # Required if selectOrConfig is 'config'
          nuGetVersion: '3.0.0' # Specify the NuGet version
